import { Outfit } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/_components/Header"; // This is fine, you only need to render it here
import NextAuthSessionProvider from "@/app/provider";
import { AuthProvider } from '@descope/nextjs-sdk';

const inter = Outfit({subsets: ['latin']});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <AuthProvider projectId="P2pomum8zfuD5JaEEKYJ6yxKLVo0">
            <html lang="en">
            <body className={inter.className}>
            <NextAuthSessionProvider>
                <div className="mx-6 md:mx-16">
                    <Header /> {/* Header is rendered globally here */}
                    {children} {/* Page-specific content goes here */}
                </div>
            </NextAuthSessionProvider>
            </body>
            </html>
        </AuthProvider>
    );
}
